-----------  REGISTRATION ----------------
Insert into ADC_REF_CD_VAL
   (REF_CD_VAL_SEQ, REF_CD_GRP_CODE, REF_CD_VAL_CODE, REF_CD_VAL_DESC, REF_CD_VAL_SHRT_DESC, 
    REMARKS, CRNT_REC_FLG, CRTD_DT, CRTD_BY, LAST_UPD_AT, 
    LAST_UPD_BY)
 Values
   (REF_CD_GRP_VAL_SEQ.NEXTVAL, '0001', '0011', 'BOP', 'BOP-DSB', 
    'Bank of Punjab Disbursements', 1, SYSDATE, 'yousaf.ali', NULL, 
    NULL);

-----------------   INQUIRY AND PAYMENTS ----------

Insert into ADC_REF_CD_GRP
   (REF_CD_GRP_SEQ, REF_CD_GRP_CODE, REF_CD_GRP_DESC, REF_CD_GRP_SHRT_DESC, REMARKS, 
    CRNT_REC_FLG, CRTD_DT, CRTD_BY, LAST_UPD_AT, LAST_UPD_BY)
 Values
   (REF_CD_GRP_VAL_SEQ.NEXTVAL, '0018', 'INQUIRY RESPONSE STATUS (BOP DISBURSEMENTS)', 'INQ-BOP', NULL, 
    1, SYSDATE, 'YOUSAF.ALI', NULL, NULL);
    
Insert into ADC_REF_CD_GRP
   (REF_CD_GRP_SEQ, REF_CD_GRP_CODE, REF_CD_GRP_DESC, REF_CD_GRP_SHRT_DESC, REMARKS, 
    CRNT_REC_FLG, CRTD_DT, CRTD_BY, LAST_UPD_AT, LAST_UPD_BY)
 Values
   (REF_CD_GRP_VAL_SEQ.NEXTVAL, '0019', 'PAYMENT RESPONSE STATUS BOP DISBURSEMENTS)', 'PYMT-BOP', NULL, 
    1, SYSDATE, 'YOUSAF.ALI', NULL, NULL);
    
----------------  INQUIRIES RESPONSES ----------------

Insert into ADC_REF_CD_VAL
   (REF_CD_VAL_SEQ, REF_CD_GRP_CODE, REF_CD_VAL_CODE, REF_CD_VAL_DESC, REF_CD_VAL_SHRT_DESC, 
    REMARKS, CRNT_REC_FLG, CRTD_DT, CRTD_BY, LAST_UPD_AT, 
    LAST_UPD_BY)
 Values
   (REF_CD_GRP_VAL_SEQ.NEXTVAL, '0018', '0000', 'VALID CONSUMER NUMBER THAT EXISTS IN THE SYSTEM/DATABASE OF MFI', ' ', 
    'INQUIRY PAYMENT STATUS', 1, SYSDATE, 'YOUSAF.ALI', NULL, 
    NULL);
    
Insert into ADC_REF_CD_VAL
   (REF_CD_VAL_SEQ, REF_CD_GRP_CODE, REF_CD_VAL_CODE, REF_CD_VAL_DESC, REF_CD_VAL_SHRT_DESC, 
    REMARKS, CRNT_REC_FLG, CRTD_DT, CRTD_BY, LAST_UPD_AT, 
    LAST_UPD_BY)
 Values
   (REF_CD_GRP_VAL_SEQ.NEXTVAL, '0018', '0001', 'INVALID CONSUMER NUMBER. CONSUMER NUMBER DOES NOT EXIST', ' ', 
    'INQUIRY PAYMENT STATUS', 1, SYSDATE, 'YOUSAF.ALI', NULL, 
    NULL);
    
Insert into ADC_REF_CD_VAL
   (REF_CD_VAL_SEQ, REF_CD_GRP_CODE, REF_CD_VAL_CODE, REF_CD_VAL_DESC, REF_CD_VAL_SHRT_DESC, 
    REMARKS, CRNT_REC_FLG, CRTD_DT, CRTD_BY, LAST_UPD_AT, 
    LAST_UPD_BY)
 Values
   (REF_CD_GRP_VAL_SEQ.NEXTVAL, '0018', '0002', 'ERROR/EXCEPTION', ' ', 
    'INQUIRY PAYMENT STATUS', 1, SYSDATE, 'YOUSAF.ALI', NULL, 
    NULL);
    
Insert into ADC_REF_CD_VAL
   (REF_CD_VAL_SEQ, REF_CD_GRP_CODE, REF_CD_VAL_CODE, REF_CD_VAL_DESC, REF_CD_VAL_SHRT_DESC, 
    REMARKS, CRNT_REC_FLG, CRTD_DT, CRTD_BY, LAST_UPD_AT, 
    LAST_UPD_BY)
 Values
   (REF_CD_GRP_VAL_SEQ.NEXTVAL, '0018', '0003', 'INVALID USER/PASSWROD', ' ', 
    'INQUIRY PAYMENT STATUS', 1, SYSDATE, 'YOUSAF.ALI', NULL, 
    NULL);
    
Insert into ADC_REF_CD_VAL
   (REF_CD_VAL_SEQ, REF_CD_GRP_CODE, REF_CD_VAL_CODE, REF_CD_VAL_DESC, REF_CD_VAL_SHRT_DESC, 
    REMARKS, CRNT_REC_FLG, CRTD_DT, CRTD_BY, LAST_UPD_AT, 
    LAST_UPD_BY)
 Values
   (REF_CD_GRP_VAL_SEQ.NEXTVAL, '0018', '0004', 'INVALID DATA', ' ', 
    'INQUIRY PAYMENT STATUS', 1, SYSDATE, 'YOUSAF.ALI', NULL, 
    NULL);
    
Insert into ADC_REF_CD_VAL
   (REF_CD_VAL_SEQ, REF_CD_GRP_CODE, REF_CD_VAL_CODE, REF_CD_VAL_DESC, REF_CD_VAL_SHRT_DESC, 
    REMARKS, CRNT_REC_FLG, CRTD_DT, CRTD_BY, LAST_UPD_AT, 
    LAST_UPD_BY)
 Values
   (REF_CD_GRP_VAL_SEQ.NEXTVAL, '0018', '0005', 'PROCESSING FAILED', ' ', 
    'INQUIRY PAYMENT STATUS', 1, SYSDATE, 'YOUSAF.ALI', NULL, 
    NULL);
    
----------------  PAYMENT RESPONSES ----------------
Insert into ADC_REF_CD_VAL
   (REF_CD_VAL_SEQ, REF_CD_GRP_CODE, REF_CD_VAL_CODE, REF_CD_VAL_DESC, REF_CD_VAL_SHRT_DESC, 
    REMARKS, CRNT_REC_FLG, CRTD_DT, CRTD_BY, LAST_UPD_AT, 
    LAST_UPD_BY)
 Values
   (REF_CD_GRP_VAL_SEQ.NEXTVAL, '0019', '0000', 'SUCCESSFUL', ' ', 
    'INQUIRY PAYMENT STATUS', 1, SYSDATE, 'YOUSAF.ALI', NULL, 
    NULL);
    
Insert into ADC_REF_CD_VAL
   (REF_CD_VAL_SEQ, REF_CD_GRP_CODE, REF_CD_VAL_CODE, REF_CD_VAL_DESC, REF_CD_VAL_SHRT_DESC, 
    REMARKS, CRNT_REC_FLG, CRTD_DT, CRTD_BY, LAST_UPD_AT, 
    LAST_UPD_BY)
 Values
   (REF_CD_GRP_VAL_SEQ.NEXTVAL, '0019', '0001', 'INVALID CONSUMER NUMBER. CONSUMER NUMBER DOES NOT EXIST', ' ', 
    'INQUIRY PAYMENT STATUS', 1, SYSDATE, 'YOUSAF.ALI', NULL, 
    NULL);
    
Insert into ADC_REF_CD_VAL
   (REF_CD_VAL_SEQ, REF_CD_GRP_CODE, REF_CD_VAL_CODE, REF_CD_VAL_DESC, REF_CD_VAL_SHRT_DESC, 
    REMARKS, CRNT_REC_FLG, CRTD_DT, CRTD_BY, LAST_UPD_AT, 
    LAST_UPD_BY)
 Values
   (REF_CD_GRP_VAL_SEQ.NEXTVAL, '0019', '0002', 'DUPLICATE TRANSACTION/ ALREADY PAID', ' ', 
    'INQUIRY PAYMENT STATUS', 1, SYSDATE, 'YOUSAF.ALI', NULL, 
    NULL);
    
Insert into ADC_REF_CD_VAL
   (REF_CD_VAL_SEQ, REF_CD_GRP_CODE, REF_CD_VAL_CODE, REF_CD_VAL_DESC, REF_CD_VAL_SHRT_DESC, 
    REMARKS, CRNT_REC_FLG, CRTD_DT, CRTD_BY, LAST_UPD_AT, 
    LAST_UPD_BY)
 Values
   (REF_CD_GRP_VAL_SEQ.NEXTVAL, '0019', '0003', 'INVALID USER/PASSWROD', ' ', 
    'INQUIRY PAYMENT STATUS', 1, SYSDATE, 'YOUSAF.ALI', NULL, 
    NULL);
    
Insert into ADC_REF_CD_VAL
   (REF_CD_VAL_SEQ, REF_CD_GRP_CODE, REF_CD_VAL_CODE, REF_CD_VAL_DESC, REF_CD_VAL_SHRT_DESC, 
    REMARKS, CRNT_REC_FLG, CRTD_DT, CRTD_BY, LAST_UPD_AT, 
    LAST_UPD_BY)
 Values
   (REF_CD_GRP_VAL_SEQ.NEXTVAL, '0019', '0004', 'INVALID DATA USER/PASSWORD/BANK CODE', ' ', 
    'INQUIRY PAYMENT STATUS', 1, SYSDATE, 'YOUSAF.ALI', NULL, 
    NULL);
    
Insert into ADC_REF_CD_VAL
   (REF_CD_VAL_SEQ, REF_CD_GRP_CODE, REF_CD_VAL_CODE, REF_CD_VAL_DESC, REF_CD_VAL_SHRT_DESC, 
    REMARKS, CRNT_REC_FLG, CRTD_DT, CRTD_BY, LAST_UPD_AT, 
    LAST_UPD_BY)
 Values
   (REF_CD_GRP_VAL_SEQ.NEXTVAL, '0019', '0005', 'SERVICE FAIL', ' ', 
    'INQUIRY PAYMENT STATUS', 1, SYSDATE, 'YOUSAF.ALI', NULL, 
    NULL);

Insert into ADC_REF_CD_VAL
   (REF_CD_VAL_SEQ, REF_CD_GRP_CODE, REF_CD_VAL_CODE, REF_CD_VAL_DESC, REF_CD_VAL_SHRT_DESC, 
    REMARKS, CRNT_REC_FLG, CRTD_DT, CRTD_BY, LAST_UPD_AT, 
    LAST_UPD_BY)
 Values
   (REF_CD_GRP_VAL_SEQ.NEXTVAL, '0019', '0006', 'LOAN REVERSED', ' ', 
    'INQUIRY PAYMENT STATUS', 1, SYSDATE, 'YOUSAF.ALI', NULL, 
    NULL);
